apiVersion: batch/v1
kind: Job
metadata:
  name: app-wxwork
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: wxwork-notification
        image: curlimages/curl
        command:
          - "curl"
          - "--request"
          - "POST"
          - "http://192.168.160.1:8080/"
          - "--header"
          - "'Content-Type: application/json'"
          - "--data-raw"
          - "{\"msgtype\": \"text\",\"text\": {\"content\": \"hello world\"}}"
      restartPolicy: Never
  backoffLimit: 1
